[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "multilingual-voice-tutor"

[services.variables]
PORT = "8080"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"
