[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "streamlit run multilingual_voice_tutor_enhanced.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false"
